### PR TITLE
User orders

### PR DESCRIPTION
**Pull request by fterdal**
Renders a minimal list of user's orders on (on /orders)

### CODE REVIEW

**Review by RobertShaw1 — CHANGES_REQUESTED** [review]
I added a comment and a change for the user-orders component

**Review by RobertShaw1 — APPROVED** [review]
This looks good!

**Review by RobertShaw1 — APPROVED** [review]
Love the commit message.  Everything looking fine.

**Comment by fterdal** [comment]
@RobertShaw1 That makes sense. I can do some more work on it, and we can review it together.

**Review by ghanley — APPROVED** [review]

**Pull request merged**
